openapi: 3.0.3
info:
  title: Carrier Billing Checkout
  description: |-
    Service that provides functionality for enabling the purchase and payment of goods against OB carrier billing systems.

    # Relevant Definitions and concepts

    - **Purchase**: The action of acquiring a good, service or product.
    - **Payment**: The act or process of paying for that good, service or product.
    - **Payable**: The concept, service or good a client is paying for.

    # API functionality

    This API allows to create and pay purchases of several Payables. Initial scope is focused in the purchase of digital goods via OB carrier billing systems.

    # Resources and Operations overview

     There are 2 resources in the API:
    - The first one, **Purchases**, exposes two operations that allow to create and retrieve purchase info for a specific user. The unique supported **payable** so far is:
      - **Digital Good:** Good that the user will acquire, provided by a third party (not the OB) (e.g.: purchase "extra" credit in online gaming, transport tickets, etc).

    - **Payments** is the second one and it exposes four operations to **request the payment** of a specific purchase via OB carrier billing systems **in one-step** (payment request) **or two-step** (payment preparation, payment confirmation or payment cancellation):
      - **Carrier Billing:** It means that the operator will perform the billing, accordingly to the user's configuration in the OB; usually this implies that the purchase will be included in the user invoice and then charged to the user, but actually other options may eventually happen, like charge against user prepay balance or other. Notice that this option do not explicitly define the actual payment method, but means that the carrier will be doing the charge based on configuration out of scope of this API.
      
      - The last resource is **Purchase Notifications**. This resource has one operation to send events to the `notification_url`, when provided by the API client in the purchase creation.
    
    Sequence Diagram: ![Sequence Diagram](https://github.com/camaraproject/CarrierBillingCheckOut/blob/main/documentation/API_documentation/resources/Carrier_Billing_Checkout_sequence_diagram.png)
  termsOfService: http://swagger.io/terms/
  contact:
    email: project-email@sample.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.7.0
externalDocs:
  description: Product documentation at Camara
  url: https://github.com/camaraproject/
security:
  - three_legged:
    - carrier-billing-checkout-purchase-digital-good-user-write
    - carrier-billing-checkout-purchase-digital-good-user-read
    - carrier-billing-checkout-payment-user-write
    - carrier-billing-checkout-user-notifications
servers:
  - url: "{apiRoot}/{basePath}"
    variables:
      apiRoot:
        default: http://localhost:9091
        description: API root
      basePath:
        default: carrier-billing-checkout/v0
        description: Base path for the Carrier Billing Checkout API
paths:
  /purchases:
    post:
      tags:
        - Purchases
      summary: Creates a new purchase
      description: Creates a new Purchase for a given payable
      operationId: createPurchase
      security:
        - three_legged:
          - carrier-billing-checkout-purchase-digital-good-user-write
      parameters:
        - $ref: '#/components/parameters/x-correlator'
      requestBody:
        description: Creates a new purchase
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePurchase"
        required: true
      callbacks:
        notifications:
          "{$request.body#/notificationUrl}/notifications":
            $ref: "#/paths/~1notifications"
      responses:
        "201":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Purchase created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseCreated"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic403:
                  summary: Forbidden
                  value: 
                    status: 403
                    code: PERMISSION_DENIED
                    message: "Operation not allowed: ..."
                RegulationTransactionAmountOverpassed:
                  summary: Purchase amount overpassed according to applicable regulation
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.PURCHASE_AMOUNT_OVERPASSED
                    message: "Purchase amount overpasses applicable regulation"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
    get:
      tags:
        - Purchases
      summary: Retrieve a list of purchases
      description: Obtain the list of purchases performed. If no pagination is indicated, list of purchases performed in the last 24 hours are returned.
      operationId: getPurchases
      security:
        - three_legged:
          - carrier-billing-checkout-purchase-digital-good-user-read
      parameters:
        - $ref: '#/components/parameters/x-correlator'
        - $ref: '#/components/parameters/Page'
        - $ref: '#/components/parameters/PerPage'
        - $ref: '#/components/parameters/Seek'
      responses:
        "200":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
            Content-Last-Key:
              $ref: '#/components/headers/Content-Last-Key'
            X-Total-Count:
              $ref: '#/components/headers/X-Total-Count'
          description: Contains information about a list of purchases
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Purchases"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
  /purchases/{purchaseId}:
    get:
      tags:
        - Purchases
      summary: Retrieve Purchase Information
      description: Get Purchase Information of a given payable
      operationId: getPurchaseInfo
      security:
        - three_legged:
          - carrier-billing-checkout-purchase-digital-good-user-read
      parameters:
        - $ref: '#/components/parameters/x-correlator'
        - name: purchaseId
          in: path
          description: Purchase ID that was obtained from the createPurchase operation
          required: true
          schema:
            $ref: "#/components/schemas/PurchaseId"
      responses:
        "200":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Contains information about a given purchase
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PurchaseInfo"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
  /purchases/{purchaseId}/payment:
    post:
      tags:
        - Payments
      summary: Creates a new Payment for a given payable in one-step
      description: Creates a new Payment Procedure for a given payable. Once this operation is successful, payment process is triggered and no further action is required, that is, no other payment attempt must be done over the same purchaseId (error code 409 will be triggered). In case a payment attempt over a specific purchaseId ends with error, a new one attempt is allowed with the same conditions.
      operationId: createPayment
      security:
        - three_legged:
          - carrier-billing-checkout-payment-user-write
      parameters:
        - $ref: '#/components/parameters/x-correlator'
        - name: purchaseId
          in: path
          description: Purchase ID that was obtained from the createPurchase operation
          required: true
          schema:
            $ref: "#/components/schemas/PurchaseId"
      requestBody:
        description: Request a new Payment
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPayment"
        required: true
      responses:
        "200":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Payment Performed
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaymentInfo"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic403:
                  summary: Forbidden
                  value: 
                    status: 403
                    code: PERMISSION_DENIED
                    message: "Operation not allowed: ..."
                PhoneNumberRequired:
                  summary: Phone Number not provided and cannot be obtained from Authorization context
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.PHONE_NUMBER_REQUIRED
                    message: "Phone Number is required"
                PhoneNumberMismatch:
                  summary: Phone Number provided not matching Authorization context
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.INVALID_TOKEN_CONTEXT
                    message: "Phone Number does not match with Authorization context"
                RegulationAccumulatedTransactionAmountOverpassed:
                  summary: Accumulated Purchases amount overpassed according to applicable regulation
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.ACCUMULATED_PURCHASE_AMOUNT_OVERPASSED
                    message: "Accumulated Purchases Amount overpasses applicable regulation"
        "404":
          $ref: "#/components/responses/Generic404"
        "409":
          $ref: "#/components/responses/Generic409"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
  /purchases/{purchaseId}/payment/prepare:
    post:
      tags:
        - Payments
      summary: Creates a new Payment for a given payable in two-step
      description: Creates a new Payment Procedure for a given payable. Once this operation is successful, payment process is reserved but not completely triggered/fulfilled. A second explicit action is required to confirm or cancel the payment.
      operationId: preparePayment
      security:
        - three_legged:
          - carrier-billing-checkout-payment-user-write
      parameters:
        - $ref: '#/components/parameters/x-correlator'
        - name: purchaseId
          in: path
          description: Purchase ID that was obtained from the createPurchase operation
          required: true
          schema:
            $ref: "#/components/schemas/PurchaseId"
      requestBody:
        description: Request a new Payment
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RequestPayment"
        required: true
      responses:
        "200":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Payment Triggered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PreparePaymentInfo"
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic403:
                  summary: Forbidden
                  value: 
                    status: 403
                    code: PERMISSION_DENIED
                    message: "Operation not allowed: ..."
                PhoneNumberRequired:
                  summary: Phone Number not provided and cannot be obtained from Authorization context
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.PHONE_NUMBER_REQUIRED
                    message: "Phone Number is required"
                PhoneNumberMismatch:
                  summary: Phone Number provided not matching Authorization context
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.INVALID_TOKEN_CONTEXT
                    message: "Phone Number does not match with Authorization context"
                RegulationAccumulatedTransactionAmountOverpassed:
                  summary: Accumulated Purchases amount overpassed according to applicable regulation
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.ACCUMULATED_PURCHASE_AMOUNT_OVERPASSED
                    message: "Accumulated Purchases Amount overpasses applicable regulation"
        "404":
          $ref: "#/components/responses/Generic404"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
  /purchases/{purchaseId}/payment/confirm:
    post:
      tags:
        - Payments
      summary: Confirm a Payment
      description: Confirms a Payment for a given payable
      operationId: confirmPayment
      security:
        - three_legged:
          - carrier-billing-checkout-payment-user-write
      parameters:
        - $ref: '#/components/parameters/x-correlator'
        - name: purchaseId
          in: path
          description: Purchase ID that was obtained from the createPurchase operation
          required: true
          schema:
            $ref: "#/components/schemas/PurchaseId"
      responses:
        "202":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Payment Accepted
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic403:
                  summary: Forbidden
                  value: 
                    status: 403
                    code: PERMISSION_DENIED
                    message: "Operation not allowed: ..."
                RegulationAccumulatedTransactionAmountOverpassed:
                  summary: Accumulated Purchases amount overpassed according to applicable regulation
                  value: 
                    status: 403
                    code: CARRIER_BILLING_CHECKOUT.ACCUMULATED_PURCHASE_AMOUNT_OVERPASSED
                    message: "Accumulated Purchases Amount overpasses applicable regulation"
        "404":
          $ref: "#/components/responses/Generic404"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic409:
                  summary: Conflict
                  value: 
                    status: 409
                    code: ALREADY_EXISTS
                    message: "Another payment confirmation or cancellation has been triggered for the same purchase"
                PaymentAlreadyReachedFinalStatus:
                  summary: Payment already reached a final status for the purchase
                  value: 
                    status: 409
                    code: CARRIER_BILLING_CHECKOUT.PAYMENT_REACHED_FINAL_STATUS
                    message: "Payment already reached a final status. No further actions can be performed"
        "412":
          $ref: "#/components/responses/Generic412"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
  /purchases/{purchaseId}/payment/cancel:
    post:
      tags:
        - Payments
      summary: Cancel a Payment
      description: Cancels a Payment for a given payable
      operationId: cancelPayment
      security:
        - three_legged:
          - carrier-billing-checkout-payment-user-write
      parameters:
        - $ref: '#/components/parameters/x-correlator'
        - name: purchaseId
          in: path
          description: Purchase ID that was obtained from the createPurchase operation
          required: true
          schema:
            $ref: "#/components/schemas/PurchaseId"
      responses:
        "202":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Payment Cancellation Accepted
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "404":
          $ref: "#/components/responses/Generic404"
        "409":
          description: Conflict
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInfo"
              examples:
                Generic409:
                  summary: Conflict
                  value: 
                    status: 409
                    code: ALREADY_EXISTS
                    message: "Another payment confirmation or cancellation has been triggered for the same purchase"
                PaymentAlreadyReachedFinalStatus:
                  summary: Payment already reached a final status for the purchase
                  value: 
                    status: 409
                    code: CARRIER_BILLING_CHECKOUT.PAYMENT_REACHED_FINAL_STATUS
                    message: "Payment already reached a final status. No further actions can be performed"
        "412":
          $ref: "#/components/responses/Generic412"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
  /notifications:
    post:
      tags:
        - Purchase Notifications
      summary: "Purchase notifications"
      description: |
        Important: this endpoint is to be implemented by the API consumer.
        The Carrier Billing Checkout server will call this endpoint whenever any purchase related event occurs.
      operationId: purchaseNotification
      parameters:
        - $ref: '#/components/parameters/x-correlator'
      requestBody:
        description: Creates a new purchase Notification
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Notification"
        required: true
      responses:
        "204":
          headers:
            x-correlator:
              $ref: '#/components/headers/x-correlator'
          description: Successful notification
        "400":
          $ref: "#/components/responses/Generic400"
        "401":
          $ref: "#/components/responses/Generic401"
        "403":
          $ref: "#/components/responses/Generic403"
        "500":
          $ref: "#/components/responses/Generic500"
        "503":
          $ref: "#/components/responses/Generic503"
        "504":
          $ref: "#/components/responses/Generic504"
      security:
        - apiKey: []
components:
  securitySchemes:
    three_legged:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.example.com/authorize
          tokenUrl: https://auth.example.com/token
          scopes:
            carrier-billing-checkout-purchase-digital-good-user-write: create purchases
            carrier-billing-checkout-purchase-digital-good-user-read: read purchases
            carrier-billing-checkout-payment-user-write: make payments
            carrier-billing-checkout-user-notifications: read notifications
    apiKey:
      type: apiKey
      description: API key to authorize requests
      name: apikey
      in: query
  schemas:
    CreatePurchase:
      allOf:
        - $ref: '#/components/schemas/PurchaseBase'
        - type: object
          properties:
            notificationAuthToken:
              type: string
              example: "18dfdf79-e29b-41d4-a716-446655440000"
              description: Authentication token for callback API endpoint
        - additionalProperties: false
    PurchaseCreated:
      allOf:
        - $ref: '#/components/schemas/PurchaseBase'
        - type: object
          properties:
            id:
              type: string
              format: uuid
              description: Unique Identifier of the purchase transaction
            status:
              type: string
              enum:
                - initialising
                - ready_to_confirm
                - processing
                - succeeded
                - failed
                - cancelled
              description: |
                * `initialising` - Purchase process is triggered
                * `ready_to_confirm` - PreparePayment has been successfully accomplished
                * `processing` - ConfirmPayment has been successfully triggered
                * `succeeded` - Purchase payment has been successfully executed
                * `failed` - Purchase process failed at any step. New purchase needs to be triggered
                * `cancelled` - CancelPayment has been successfully accomplished
            notificationAuthToken:
              type: string
              example: "18dfdf79-e29b-41d4-a716-446655440000"
              description: Authentication token for callback API endpoint
          required:
            - id
            - status
          additionalProperties: false
    PurchaseBase:
      type: object
      description: Basic Representation of a Purchase Context
      properties:
        payable:
          $ref: '#/components/schemas/PolymorphicPayable'
        notificationUrl:
          type: string
          pattern: '^https:\/\/.+$'
          description: Callback URL where service is going to be notified about any event. The received body definition is indicated in _Purchase notifications_ endpoint.
          example: https://notifications-service.com/purchases/
      required:
        - payable
    PolymorphicPayable:
      type: object
      description: Basic representation of a payable resource/entity. Please refer to the Model to see all possible instances of Payable
      properties:
        type:
          type: string
          description: Type of payable
      required:
        - type
      discriminator:
        propertyName: type
        mapping:
          digital_good: "#/components/schemas/DigitalGood"
      oneOf:
        - $ref: "#/components/schemas/DigitalGood"
    DigitalGood:
      description: Basic representation of a digital good, including the total sum of all amount of the items.
      allOf:
        - $ref: '#/components/schemas/PolymorphicPayable'
        - $ref: '#/components/schemas/MerchantInfo'
      example:
        type: digital_good
        order:
          id: MarketOrder1
          items:
            - name: MarketOrderItemName1
              amount:
                value: 25
                currency: EUR
                taxIncluded: true
            - name: MarketOrderItemName2
              amount:
                value: 40
                currency: EUR
                taxIncluded: true
          totalAmount:
            value: 65
            currency: EUR
            taxIncluded: true
        merchant:
          id: MerchantId1
          name: MerchantName1
          fee: 15.45
    MerchantInfo:
      type: object
      description: Represents a collection of goods belonging to a external merchant/provider to be paid
      properties:
        merchant:
          $ref: '#/components/schemas/MarketMerchant'
        order:
          $ref: '#/components/schemas/MarketOrder'
      required:
        - order
    MarketMerchant:
      type: object
      description: Represents a merchant/provider from external market
      properties:
        id:
          type: string
          description: Unique identifier of the merchant
        name:
          type: string
          description: Merchant description
        fee:
          type: number
          format: float
          description: Fee percentage for the merchant/provider
      required:
        - id
      example:
        id: MerchantId1
        name: MerchantName1
        fee: 15.45
    MarketOrder:
      type: object
      description: Represents an order from external market
      properties:
        id:
          type: string
          description: Unique identifier of the order on the merchant/provider external system. Only provided when relevant from the API client point of view.
        items:
          type: array
          minItems: 1
          items:
            $ref: '#/components/schemas/MarketOrderItem'
        totalAmount:
          $ref: '#/components/schemas/MoneyAmount'
      required:
        - items
        - totalAmount
      example:
        id: MarketOrder1
        items:
          - name: MarketOrderItemName1
            amount:
              value: 25
              currency: EUR
              taxIncluded: true
          - name: MarketOrderItemName2
            amount:
              value: 40
              currency: EUR
              taxIncluded: true
        totalAmount:
          value: 65
          currency: EUR
          taxIncluded: true
    MarketOrderItem:
      type: object
      description: A item from external merchant/provider to be paid during checkout
      properties:
        name:
          type: string
          description: Item description provided by external merchant
        amount:
          $ref: '#/components/schemas/MoneyAmount'
      required:
        - name
        - amount
      example:
        name: MarketOrderItemName1
        amount:
          value: 25
          currency: EUR
          taxIncluded: true
    MoneyAmount:
      type: object
      description: Money amount
      properties:
        value:
          type: number
          format: float
          multipleOf: 0.01
          description: Amount value
        currency:
          type: string
          description: Currency code in which the amount is expressed. ISO 4217
        taxIncluded:
          type: boolean
          description: true if the amount includes government taxes
          default: false
      required:
        - value
        - currency
    PurchaseId:
      type: string
      format: uuid
      description: Unique Purchase identifier
    PurchaseInfo:
      allOf:
        - $ref: '#/components/schemas/PurchaseBase'
        - type: object
          properties:
            id:
              type: string
              format: uuid
              description: Unique Identifier of the purchase transaction
            status:
              type: string
              enum:
                - initialising
                - ready_to_confirm
                - processing
                - succeeded
                - failed
                - cancelled
              description: |
                * `initialising` - Purchase process is triggered
                * `ready_to_confirm` - PreparePayment has been successfully accomplished
                * `processing` - ConfirmPayment has been successfully triggered
                * `succeeded` - ConfirmPayment has been successfully executed
                * `failed` - Purchase process failed at any step. New purchase needs to be triggered
                * `cancelled` - CancelPayment has been successfully accomplished
            paymentCreationDate:
              type: string
              format: date-time
              description: Date, in ISO-8601 extended local date format, when the payment is created in server database. This is a technical information. Time-offset from UTC may be used to match local OB time.
            paymentDate:
              type: string
              format: date-time
              description: Date, in ISO-8601 extended local date format, when the payment is effectively performed. This is a business information. Time-offset from UTC may be used to match local OB time.
          required:
            - id
            - status
          additionalProperties: false
    Purchases:
      type: array
      items:
        $ref: '#/components/schemas/PurchaseInfo'
    RequestPayment:
      type: object
      description: Data Type to indicate in payment request, either 1-step or 2-step.
      properties:
        phoneNumber:
          type: string
          description: The MSISDN on which the payment will be performed, in E.164 with `+` format. If no indicated, MSISDN has to be obtained from authorization context (i.e. Authorization header), otherwise exception will be raised.
      example:
        phoneNumber: '+34699999999'
    PaymentInfo:
      type: object
      description: Data Type to indicate payment information
      properties:
        id:
          type: string
          format: uuid
          description: Unique Identifier of the purchase transaction
        status:
          type: string
          description: |
            * `succeeded` - Payment has been successfully executed
            * `failed` - Purchase process failed at any step. New purchase needs to be triggered
          enum:
            - succeeded
            - failed
      required:
        - id
        - status
    PreparePaymentInfo:
      type: object
      description: Data Type to indicate prepare payment information 
      properties:
        id:
          type: string
          format: uuid
          description: Unique Identifier of the purchase transaction
        status:
          type: string
          enum:
          - initialising
          - ready_to_confirm
          - failed
          description: |
            * `initialising` - Purchase process is triggered
            * `ready_to_confirm` - PreparePayment has been successfully accomplished
            * `failed` - Purchase process failed at any step. New purchase needs to be triggered
        paymentOtp:
          $ref: '#/components/schemas/PaymentOtp'
      required:
        - id
        - status
    PaymentOtp:
      type: object
      description: Data type to provide the necessary information in order to validate an OTP
      properties:
        validationEndpoint:
          type: string
          format: uri
          description: URL for OTP validation
        parameters:
          type: object
          description: Pairs of key/value for the parameters that have to be submitted as query parameters when calling the validation endpoint
      required:
        - validationEndpoint
    Notification:
      type: object
      description: Data type with attributes required for generating a Purchase notification
      properties:
        purchaseId:
          type: string
          description: Unique Identifier of the purchase transaction
        action:
          type: string
          enum:
            - prepare_payment
            - confirm_payment
            - cancel_payment
          description: |
            Indication of the action notified by the event.
            * `prepare_payment`: Notification about preparePayment procedure
            * `confirm_payment`: Notification about confirmPayment procedure
            * `cancel_payment`: Notificacion about cancelPayment procedure
        status:
          type: string
          enum:
            - succeeded
            - failed
          description: | 
            Status of the procedure. Possible status are:
            * `succeeded`: procedure was accomplished 
            * `failed`: procedure failed.
            
            NOTE: Under reception of a notification with failed status, new purchase procedure shall be initiated by API Client, if required.
        description:
          type: string
          description: Description of the notification, both used when process was `succeeded` or `failed` indicating in the latter case human understable reason about why process failed.
        paymentDate:
          type: string
          format: date-time
          description: Date, in ISO-8601 extended local date format, when the payment is effectively performed. This is a business information. Time-offset from UTC may be used to match local OB time.
      required:
        - purchaseId
        - action
        - status
        - description
    ErrorInfo:
      type: object
      required:
        - code
        - message
        - status
      properties:
        code:
          type: string
          description: Code given to this error
        message:
          type: string
          description: Detailed error description
        status:
          type: integer
          description: HTTP response status code
  parameters:
    x-correlator:
      name: x-correlator
      in: header
      description: Correlation id for the different services
      schema:
        type: string
    Page:
      name: page
      in: query
      description: Requested index to indicate the start of the resources to be provided in the response
      schema:
        type: integer
    PerPage:
      name: perPage
      in: query
      description: Requested number of resources to be provided in response
      schema:
        type: integer
    Seek:
      name: seek
      in: query
      description: Index of last result read to create the next/previous number of results. This query parameter is used for pagination in systems with more than 1000 records
      schema:
        type: integer
  headers:
    x-correlator:
      description: Correlation id for the different services
      schema:
        type: string
    Content-Last-Key:
      description: Indicates the index of the last result provided in the response
      schema:
        type: integer
    X-Total-Count:
      description: Indicates the total number of items in the collection (i.e. total purchases performed)
      schema:
        type: integer
  responses:
    Generic400:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Invalid input
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 400
            code: INVALID_ARGUMENT
            message: "Schema validation failed at  ..."
    Generic401:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 401
            code: UNAUTHORIZED
            message: "Authorization failed: ..."
    Generic403:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 403
            code: PERMISSION_DENIED
            message: "Operation not allowed: ..."
    Generic404:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Resource Not Found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 404
            code: NOT_FOUND
            message: "The specified resource is not found"
    Generic409:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 409
            code: ALREADY_EXISTS
            message: "A specified resource duplicate entry found"
    Generic412:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Request cannot be executed in the current system state
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 412
            code: FAILED_PRECONDITION
            message: "Request cannot be executed in the current system state"
    Generic500:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 500
            code: INTERNAL
            message: "Server error"
    Generic503:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Service unavailable
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 503
            code: SERVICE_UNAVALIBLE
            message: "Service unavailable"
    Generic504:
      headers:
        x-correlator:
          $ref: '#/components/headers/x-correlator'
      description: Request timeout exceeded
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorInfo"
          example:
            status: 504
            code: TIMEOUT
            message: "Request timeout exceeded"
